baseURL = 'https://4m3.bio/'
languageCode = 'en-us'
title = 'Growing Wine Packaging'
ignoreLogs = ['warning-goldmark-raw-html']

theme = "ananke"

[Params]
  custom_css = ["css/custom.css"]
  Social = [
    { name = "github", url = "https://github.com/miketangobravo" },
    { name = "twitter", url = "https://x.com/openvinodao" }
  ]
  Author = "Mike Tango Bravo"
  site_logo = "4m3_cube.svg"
  text_color = "green"
  favicon = "4m3_cube.svg"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
# background_color_class = "bg-washed-blue"


defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

SectionPagesMenu = "main"
Paginate = 3                  # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true



[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    languageCode = "en"

  [languages.fr]
    languageName = "Français"
    weight = 2
    contentDir = "content/fr"
    languageCode = "fr"

  [languages.es]
    languageName = "Español"
    weight = 3
    contentDir = "content/es"
    languageCode = "es"

  [languages.it]
    languageName = "Italiano"
    weight = 4
    contentDir = "content/it"
    languageCode = "it"

  [languages.ca]
    languageName = "Català"
    weight = 5
    contentDir = "content/ca"
    languageCode = "ca"

